# Chapter 01 : 파이썬 기반의 머신러닝과 생태계 이해
## 01 머신러닝의 개념
### 머신러닝 ?
> Machine Learning : 애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법
- 데이터를 기반으로 통계적 신뢰도를 강화하고 예측 오류를 최소화하기 위한 다양한 수학적 기법을 적용해 패턴을 스스로 인지하고 신뢰도 높은 예측 결과를 도출해낸다.

### 머신러닝의 분류
> 지도학습(Supervised Learning)과 비지도학습(Un-supervised Learning)

**지도학습**
- 분류
- 회귀
- 추천 시스템
- 시각/음성의 감지/인지
- 텍스트 분석, NLP

**비지도학습**
- 클러스터링
- 차원 축소
- 강화학습

## 02 파이썬 머신러닝 생태계를 구성하는 주요 패키지
**머신러닝 패키지**
- Scikit-Learn : 가장 대표적인 데이터 마이닝 기반의 머신러닝 패키지 -> 이 책에서 다룰 내용
- Tensorflow, Keras : 딥러닝 라이브러리

**행렬/선형대수/통계 패키지**
- 머신러닝의 이론적 백그라운드는 선형대수와 통계
- Numpy : 선형대수와 행렬을 다루는 패키지
- SciPy : 자연과학과 통계를 위한 다양한 패키지 (사이킷런 내 여러 패키지의 기반)

**데이터 핸들링**
- Pandas : 데이터 처리 패키지로, 2차원 데이터 처리에 특화. 행렬 기반인 넘파이의 약점 보완

**시각화**
- Matplotlib : 대표적 시각화 패키지. 
- Seaborn : Matplotlib의 단점(너무 세분화된 API, 디자인적 투박함 등)을 보완하는 시각화 패키지

**기타 서드파티 라이브러리**
- Graphviz, KoNLPy, Surprise 등

## 03 넘파이
### 넘파이 ?
> Numpy : Numerical Python. 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적 패키지. 루프를 사용하지 않고 대량 데이터의 배열 연산이 가능하며, 빠른 배열 연산 속도를 보장한다.

### 넘파이 ndarray 개요
- array() 함수 : 파이썬의 리스트와 같은 다양한 인자의 입력을 받아 ndarray로 변환하는 기능 수행. 
- 생성된 ndarray 배열의 shape 변수는 ndarray의 크기, 즉 행과 열의 수를 튜플 형태로 가지고 있다.

In [8]:
# 넘파이 모듈 임포트
import numpy as np 

# array 생성
print('1차원 array 생성')
array1 = np.array([1, 2, 3])
print('array1 : ', array1)
print('array1 type : ', type(array1))
print('array1 array 형태 : ', array1.shape, ' -> tuple 형태로 표현')
print()

print('2차원 array 생성')
array2 = np.array([[1, 2, 3],[2,3,4]]) # list에 list를 한 번 더 묶는다.
print('array2 : ', array2)
print('array2 type : ', type(array2))
print('array2 array 형태 : ', array2.shape, ' -> tuple 형태로 표현')
print()

print('2차원 array 생성 (로우가 1개(inner list를 한 개만 작성)이나, 2차원인 경우)')
array2_1 = np.array([[1, 2, 3]])
print('array2_1 : ', array2_1)
print('array2_1 type : ', type(array2_1))
print('array2_1 array 형태 : ', array2_1.shape, ' -> tuple 형태로 표현')
print()

# 각 array의 차원 확인하기
print('array dimension check (ndim)')
print('array1 : {:0}차원, array2 : {:1}차원, array2_1 : {:2}차원'.format(array1.ndim,array2.ndim, array2_1.ndim))

1차원 array 생성
array1 :  [1 2 3]
array1 type :  <class 'numpy.ndarray'>
array1 array 형태 :  (3,)  -> tuple 형태로 표현

2차원 array 생성
array2 :  [[1 2 3]
 [2 3 4]]
array2 type :  <class 'numpy.ndarray'>
array2 array 형태 :  (2, 3)  -> tuple 형태로 표현

2차원 array 생성 (로우가 1개(inner list를 한 개만 작성)이나, 2차원인 경우)
array2_1 :  [[1 2 3]]
array2_1 type :  <class 'numpy.ndarray'>
array2_1 array 형태 :  (1, 3)  -> tuple 형태로 표현

array dimension check (ndim)
array1 : 1차원, array2 : 2차원, array2_1 :  2차원


### ndarray의 데이터 타입
- 숫자 값, 문자열 값, bool 값 등이 모두 가능하며, 숫자형의 경우 int형(8/16/32 bit), unsigned int형(8/16/32 bit), float형(16/32/64/128 bit), complex 타입(더 큰 숫자 값이나 정밀도를 위해)도 제공
- 같은 데이터 타입끼리만 연산 가능 (한 개의 ndarray 객체에 int와 float 공존 불가)

**데이터 타입 확인**
- dtype : 데이터 타입 확인

In [11]:
# 파이썬의 type함수와 넘파이의 .dtype 속성
list1 = [1, 2, 3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))

print(array1, array1.dtype)
print()

print('다른 데이터 유형이 섞인 리스트를 ndarray로 변경하는 경우 : ')
list2 = [1, 2, 'test'] # 숫자 + 문자
array2 = np.array(list2)
print(array2, array2.dtype, ' -> 유니코드 문자열 값으로 변환된다.')

list3 = [1, 2, 3.0] # int와 float
array3 = np.array(list3)
print(array3, array3.dtype, ' -> float 값으로 변환된다.')

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32

다른 데이터 유형이 섞인 리스트를 ndarray로 변경하는 경우 : 
['1' '2' 'test'] <U11  -> 유니코드 문자열 값으로 변환된다.
[1. 2. 3.] float64  -> float 값으로 변환된다.


**데이터 타입 변경**
- astype() : 인자로 원하는 타입을 문자열로 지정
- int형으로 충분한데, float 타입으로 작업하면 더 많은 메모리가 소요된다. 이런 경우 메모리 절약을 위해 이용한다. 

In [13]:
# astype으로 데이터 타입 변경
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print('int32 to float64 : ', array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print('float64 to int32 : ', array_int1, array_int1.dtype)

int32 to float64 :  [1. 2. 3.] float64
float64 to int32 :  [1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones
- 특정 크기와 차원의 ndarray를 연속값이나 0 또는 1로 쉽게 생성한다.
- 테스트용 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야 할 경우에 사용한다.

**arange()**
- 파이썬 표준 함수인 range()와 유사한 기능 (array를 range()로 표현하는 개념)

In [26]:
sequence_array = np.arange(10) # 최소 인자 : stop값 (0부터 1씩 증가한다.)
print(sequence_array)
print(type(sequence_array),sequence_array.dtype, sequence_array.shape)
print()

sequence_array = np.arange(0, 10, 2, dtype='int32') # np.arange(시작값, 정지값(n-1), 간격, 데이터타입 지정)
print(sequence_array)
print(type(sequence_array),sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'> int32 (10,)

[0 2 4 6 8]
<class 'numpy.ndarray'> int32 (5,)


**zeros()**
- 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운, 해당 shape를 가진 ndarray 반환

**ones()**
- 모든 값을 1로 채운 ndarray 반환

(dtype 미지정 시 default : float64)

In [25]:
zero_array = np.zeros(10, dtype='int32') # 10
print(zero_array)
print(type(zero_array), zero_array.dtype, zero_array.shape)
print()

one_array = np.ones((3,2), dtype='str') # 3행 2열, 문자형
print(one_array)
print(type(one_array), one_array.dtype, one_array.shape)

[0 0 0 0 0 0 0 0 0 0]
<class 'numpy.ndarray'> int32 (10,)

[['1' '1']
 ['1' '1']
 ['1' '1']]
<class 'numpy.ndarray'> <U1 (3, 2)


### ndarray의 차원과 크기를 변경하는 reshape()
- ndarray를 특정 차원 및 크기로 변환

In [31]:
array1 = np.arange(10)
print('array1 :\n', array1,'\n')

array2 = array1.reshape(2,5)
print('array2(2행 5열 reshape) :\n', array2, '\n')

array3 = array1.reshape(5,2)
print('array3(5행 2열 reshape) :\n', array3, '\n')

# rows*columns와 값의 길이가 일치하지 않으면 오류 발생

array1 :
 [0 1 2 3 4 5 6 7 8 9] 

array2(2행 5열 reshape) :
 [[0 1 2 3 4]
 [5 6 7 8 9]] 

array3(5행 2열 reshape) :
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 



- reshape의 인자로 -1을 적용하는 경우 : 원래 ndarray와 호환되는 새로운 shape로 변환
- reshape(-1, 1) 형태로 자주 사용된다. 여러 개의 로우를 갖되 반드시 1개의 칼럼을 가진 ndarray로 변환하는 경우
- 여러 개의 ndarray는 stack이나 concat으로 결합할 때 각각의 ndarray 형태를 통일해 유용하게 사용된다.

In [40]:
array1 = np.arange(12)
print(array1,'\n')
array2 = array1.reshape(-1, 6) # column 수를 6으로 고정하고, 데이터 개수에 따라 row 자동 설정
print(array2,'\n')
array3 = array1.reshape(4, -1) # row 수를 4로 고정하고, 데이터 개수에 따라 column 자동 설정
print(array3)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [49]:
# reshape(-1, 1) 활용
array1 = np.arange(8)
array3d = array1.reshape(2,2,2)
print('array3d :\n', array3d.tolist()) # print할 때 시각적으로 이해하기 쉽도록 리스트로 변환
print()

print('3차원 ndarray를 2차원 ndarray로 변환')
array5 = array3d.reshape(-1, 1)
print('array5 :\n', array5.tolist())
print('array5 shape : ', array5.shape, ' / array5 type : ', type(array5))
print()

print('1차원 ndarray를 2차원 ndarray로 변환')
array6 = array1.reshape(-1, 1)
print('array6 : \n', array6.tolist())
print('array6 shape : ', array6.shape, ' / array6 type : ', type(array6))

array3d :
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]

3차원 ndarray를 2차원 ndarray로 변환
array5 :
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape :  (8, 1)  / array5 type :  <class 'numpy.ndarray'>

1차원 ndarray를 2차원 ndarray로 변환
array6 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape :  (8, 1)  / array6 type :  <class 'numpy.ndarray'>


### 넘파이 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)
1. 특정한 데이터만 추출 : 원하는 위치의 인덱스 값 지정
2. 슬라이싱(Slicing) : 범위 인덱싱 [시작 index : 종료 index -1]
3. Fancy Indexing : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray 반환
4. Boolean Indexing : 특정 조건 해당 여부(True/False값)의 인덱싱 집합을 기반으로 True에 해당하는 데이터 ndarray 반환

**단일 값 추출**

In [51]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1 : ', array1)
# index는 0부터 시작하므로, array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value of array1[2] : ', value)
print(type(value))
print()

# 음수의 인덱스
print('맨 뒤의 값 : ', array1[-1], '\n 맨 뒤에서 두 번째 값 : ', array1[-2])

array1 :  [1 2 3 4 5 6 7 8 9]
value of array1[2] :  3
<class 'numpy.int32'>

맨 뒤의 값 :  9 
 맨 뒤에서 두 번째 값 :  8


- 단일 indexing으로 데이터값 수정

In [55]:
# ndarray 데이터값 수정
array1[0] = 9
array1[8] = 0
array1[-2] = 1
print('array 1 modified : ', array1)

array 1 modified :  [9 2 3 4 5 6 7 1 0]


- 다차원 ndarray에서 단일 값 추출

In [62]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)
print()

print('array2d[0,0] 값 (1행 1열): ', array2d[0,0])
print('array2d[0,1] 값 (1행 2열): ', array2d[0,1])
print('array2d[1,0] 값 (2행 1열): ', array2d[1,0])
print('array2d[2,2] 값 (3행 3열): ', array2d[2,2])

# ndarray에서는 사실 로우와 칼럼의 개념을 사용하지 않으며, axis 0, axis 1로 표현한다.
# [row=0, col=1] -> [axis 0 = 0, axis 1 = 1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

array2d[0,0] 값 (1행 1열):  1
array2d[0,1] 값 (1행 2열):  2
array2d[1,0] 값 (2행 1열):  4
array2d[2,2] 값 (3행 3열):  9


**슬라이싱**

[시작 인덱스 : 종료 인덱스 -1]

In [64]:
array1 = np.arange(1,10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [66]:
# 슬라이싱 시 숫자 생략
array1 = np.arange(start=1, stop=10)
array4 = array1[:3] # 처음(0)부터 3-1까지
print(array4)

array5 = array1[3:] # 3부터 끝(10-1)까지
print(array5)

array6 = array1[:] # 처음부터 끝까지
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


- 2차원 ndarray 슬라이싱

In [70]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d : \n', array2d)
print()

print('array2d[0:2, 0:2] : \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] : \n', array2d[1:3, 0:3])
print('array2d[1:3, :] : \n', array2d[1:3, :])
print('array2d[:, :] : \n', array2d[:, :])
print('array2d[:2, 1:] : \n', array2d[:2, 1:])
print('array2d[:2, 0] : \n', array2d[:2, 0])

array2d : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

array2d[0:2, 0:2] : 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] : 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] : 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] : 
 [[2 3]
 [5 6]]
array2d[:2, 0] : 
 [1 4]


**팬시 인덱싱(Fancy Indexing)**
: 리스트나 ndarray로 인덱스 집합을 지정해 해당 위치의 인덱스에 맞는 ndarray를 반환

In [107]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d, '\n')

array3 = array2d[[0,1], 2] # (row, col) = ((0,2), (1,2))
print('array2d[[0,1], 2] : ', array3.tolist())

array4 = array2d[[0,1,2], 0:2] # (row,col) = ((0,0), (0,1)), ((1,0),(1,1)), ((2,0),(2,1))
print('array2d[[0,1,2], 0:2] : ', array4.tolist())

array5 = array2d[[0,1]] # (row, col) = ((0, :), (1, :))
print('array2d[[0,1]] : ', array5.tolist())

array6 = array2d[[1,2], [0,2]] # (row, col) = ((1,0), (2,2))
print('array2d[[1,1], [0,2]] : ', array6.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

array2d[[0,1], 2] :  [3, 6]
array2d[[0,1,2], 0:2] :  [[1, 2], [4, 5], [7, 8]]
array2d[[0,1]] :  [[1, 2, 3], [4, 5, 6]]
array2d[[1,1], [0,2]] :  [4, 9]


[4, 9]

**불린 인덱싱(Boolean Indexing)** : 조건 필터링과 검색이 동시에 가능
- for loop/if else로 하나씩 추출값을 비교 추출하는 것보다 훨씬 간단

In [111]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 : ', array1d>5 )
print('array1d > 불린 인덱싱 결과 값 : ', array3)
# False 값은 무시하고 True 값에 해당하는 인덱스값만 저장

array1d > 5 :  [False False False False False  True  True  True  True]
array1d > 불린 인덱싱 결과 값 :  [6 7 8 9]


### 행렬의 정렬 - sort()와 argsort()
- np.sort() : 넘파이에서 sort() 호출 -> 원 행렬은 유지한 채 정렬된 행렬 반환
- ndarray.sort() : 행렬 자체에서 sort() 호출 -> 원 행렬 자체를 정렬한 형태로 변환 (반환 값은 None)
- argsort() : 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환

**행렬 정렬**

In [120]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬 : ', org_array), print()
# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬 : ', sort_array1)
print('np.sort() 호출 후 원본 행렬 : ', org_array), print()

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬 : ', sort_array2)
print('org_array.sort() 호출 후 원본 행렬 : ', org_array), print()

# 내림차순 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬 : ', sort_array1_desc), print()

# 다차원 행렬 정렬 : axis 설정
array2d = np.array([[8, 12], [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬 : \n', sort_array2d_axis0), print()

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬 : \n', sort_array2d_axis1)

원본 행렬 :  [3 1 9 5]

np.sort() 호출 후 반환된 정렬 행렬 :  [1 3 5 9]
np.sort() 호출 후 원본 행렬 :  [3 1 9 5]

org_array.sort() 호출 후 반환된 행렬 :  None
org_array.sort() 호출 후 원본 행렬 :  [1 3 5 9]

내림차순으로 정렬 :  [9 5 3 1]

로우 방향으로 정렬 : 
 [[ 7  1]
 [ 8 12]]

칼럼 방향으로 정렬 : 
 [[ 8 12]
 [ 1  7]]


**정렬된 행렬의 인덱스를 반환하기**

- argsort() : 넘파이의 ndarray는 RDBMS의 TABLE 칼럼이나 Pandas Dataframe 칼럼과 같은 메타 데이터를 가질 수 없어, 별도의 ndarray로 메타 데이터 값을 가져야 한다.

In [124]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스 : ', sort_indices)

# 내림차순 정렬
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스 : ', sort_indices_desc)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스 :  [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스 :  [2 3 0 1]


In [126]:
# ndarray 생성
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

# np.argsort()를 이용해 반환된 인덱스를 ndarray의 팬시 인덱스로 적용해 정렬
sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array 인덱스 : ', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력 : ', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array 인덱스 :  [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력 :  ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

**행렬 내적(행렬의 곱)**
- np.dot(A,B)

In [129]:
A = np.array([[1,2,3], 
              [4,5,6]])
B = np.array([[7,8], 
              [9,10], 
              [11,12]])
dot_product = np.dot(A, B)
print('행렬 내적 결과 : \n', dot_product)

행렬 내적 결과 : 
 [[ 58  64]
 [139 154]]


**전치 행렬**
- transpose()

In [131]:
C = np.array([[1,2,3], 
              [4,5,6]])
transpose_mat = np.transpose(C)
print('C의 원본 행렬 : \n', C)
print('C의 전치 행렬 : \n', transpose_mat)

C의 원본 행렬 : 
 [[1 2 3]
 [4 5 6]]
C의 전치 행렬 : 
 [[1 4]
 [2 5]
 [3 6]]


## 04 데이터 핸들링 - 판다스

### 판다스 ?
> Pandas : Wes McKinney가 개발한 Data Handling Framework. 
- 파이썬의 리스트, 컬렉션, 넘파이 등의 내부 데이터 뿐 아니라 CSV 등의 파일을 DataFrame으로 변경해 데이터 가공/분석을 편리하게 수행할 수 있다.


> - DataFrame : 판다스의 핵심 객체로, 2차원 데이터(칼럼이 여러 개)를 담는 데이터 구조체.
> - Series : 칼럼이 하나 뿐인 데이터 구조체. DataFrame은 여러 개의 Series로 이루어진다.
> - Index : 개별 데이터를 고유하게 식별하는 Key 값을 나타내는 객체. Series와 Dataframe이 key 값으로 갖는다.

### 판다스 시작 - 파일을 DataFrame으로 로딩, 기본 API
> DataFrame으로 파일을 로딩하는 편리한 API들
> - read_csv(), read_table() : 필드 구분 문자(Delimiter)가 ',' 또는 '\t'에 따라 구분. 다른 경우 sep= 옵션 추가
> - read_fwf() : Fixed Width. 고정 길이 기반의 칼럼 포맷

In [60]:
# 판다스 모듈 임포트
import pandas as pd

# Kaggle 데이터 파일 로드
titanic_df = pd.read_csv('C:/DATA_WORKS/PYTHON_WORKS/data/titanic_train.csv')
display(titanic_df.head(3))
print('titanic 변수 type : ', type(titanic_df)), print()
print('titanic DF 크기 : ', titanic_df.shape), print()
display('titanic DF 정보 : ', titanic_df.info()), print()
print('titanic 데이터 분포도 : \n', titanic_df.describe()), print()

PassengerId  Survived  Pclass                 Name     Sex   Age  SibSp  Parch  \
0            1         0       3  Braund, Mr. Owen...    male  22.0      1      0   
1            2         1       1  Cumings, Mrs. Jo...  female  38.0      1      0   
2            3         1       3  Heikkinen, Miss....  female  26.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S

titanic 변수 type :  <class 'pandas.core.frame.DataFrame'>

titanic DF 크기 :  (891, 12)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


'titanic DF 정보 : '

None


titanic 데이터 분포도 : 
        PassengerId    Survived      Pclass         Age       SibSp       Parch        Fare
count   891.000000  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std     257.353842    0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min       1.000000    0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%     446.000000    0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%     668.500000    1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000    6.000000  512.329200



(None, None)

- value_counts()

In [61]:
# titanic_df['Pclass']는 Series의 Index와 데이터 값으로 구성
display(titanic_pclass.head())

# value_counts() 적용하면 선실 등급을 Index로 받는 Series가 된다.
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)

titanic_pclass = titanic_df['Pclass']
print(type(titanic_pclass))

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

3    491
1    216
2    184
Name: Pclass, dtype: int64
<class 'pandas.core.series.Series'>


### DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환
**넘파이 ndarray, 리스트, 딕셔너리를 DataFrame으로 변환하기**

- 1차원 형태의 리스트와 ndarray -> DataFrame

In [62]:
import numpy as np
col_name1=['col1']
list1 = [1,2,3]
array1 = np.array(list1)
print('array1 shape : ', array1.shape)

# 리스트를 이용해 DataFrame 생성
df_list1 = pd.DataFrame(list1, columns = col_name1)
print('1차원 리스트로 만든 DataFrame : \n', df_list1)

# 넘파이 ndarray를 이용해 DataFrame 생성
df_array1 = pd.DataFrame(array1, columns = col_name1)
print('1차원 ndarray로 만든 DataFrame : \n', df_array1)

array1 shape :  (3,)
1차원 리스트로 만든 DataFrame : 
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame : 
    col1
0     1
1     2
2     3


- 2차원 형태의 리스트와 ndarray -> DataFrame

In [63]:
# 3개의 칼럼명 필요
col_name2 = ['col1', 'col2', 'col3']

# 2행x3열 형태의 리스트와 ndarray 생성 후 DataFrame 변환
list2 = [[1, 2, 3],
        [11, 12, 13]]
array2 = np.array(list2)
print('array2 shape : ', array2.shape)
df_list2 = pd.DataFrame(list2, columns = col_name2)
print('2차원 리스트로 만든 DataFrame : \n', df_list2)
df_array2 = pd.DataFrame(array2, columns = col_name2)
print('2차원 ndarray로 만든 DataFrame : \n', df_array2)

array2 shape :  (2, 3)
2차원 리스트로 만든 DataFrame : 
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame : 
    col1  col2  col3
0     1     2     3
1    11    12    13


- 딕셔너리를 DataFrame으로 변환

In [64]:
# Key는 문자열 칼럼명으로 매핑, Value는 리스트 형(또는 ndarray) 칼럼 데이터로 매핑
dict = {'col1':[1, 11], 'col2':[2, 22], 'col3':[3, 33]}
df_dict = pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame : \n', df_dict)

딕셔너리로 만든 DataFrame : 
    col1  col2  col3
0     1     2     3
1    11    22    33


**DataFrame을 넘파이 ndarray, 리스트, 딕셔너리로 변환하기**

In [65]:
# DataFrame을 ndarray로 변환
array3 = df_dict.values
print('df_dict.values 타입 : ', type(array3),'\n', 'df_dict.values shape : ', array3.shape)
print(array3)

df_dict.values 타입 :  <class 'numpy.ndarray'> 
 df_dict.values shape :  (2, 3)
[[ 1  2  3]
 [11 22 33]]


In [66]:
# DataFrame을 리스트로 변환
list3 = df_dict.values.tolist()
print('df_dict.values.tolist() 타입 :', type(list3))
print(list3)

df_dict.values.tolist() 타입 : <class 'list'>
[[1, 2, 3], [11, 22, 33]]


In [67]:
# DataFrame을 딕셔너리로 변환
dict3 = df_dict.to_dict('list') # 딕셔너리의 값이 리스트형으로 반환
print('\n df_dict.to_dict() 타입 : ', type(dict3))
print(dict3)


 df_dict.to_dict() 타입 :  <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


### DataFrame의 칼럼 데이터 세트 생성과 수정
- 인덱싱의 형태로 칼럼 정의하고(Series) 데이터 지정

In [68]:
# 새 칼럼 추가 (상수값 0 일괄 할당)
titanic_df['Age_0'] = 0
titanic_df.head(3)

PassengerId  Survived  Pclass                 Name     Sex   Age  SibSp  Parch  \
0            1         0       3  Braund, Mr. Owen...    male  22.0      1      0   
1            2         1       1  Cumings, Mrs. Jo...  female  38.0      1      0   
2            3         1       3  Heikkinen, Miss....  female  26.0      0      0   

             Ticket     Fare Cabin Embarked  Age_0  
0         A/5 21171   7.2500   NaN        S      0  
1          PC 17599  71.2833   C85        C      0  
2  STON/O2. 3101282   7.9250   NaN        S      0

In [69]:
# 기존 칼럼 가공하여 추가
titanic_df['Age_by_10'] = titanic_df['Age']*10
titanic_df['Family_no'] = titanic_df['SibSp'] + titanic_df['Parch']+1
titanic_df.head(3)

PassengerId  Survived  Pclass                 Name     Sex   Age  SibSp  Parch  \
0            1         0       3  Braund, Mr. Owen...    male  22.0      1      0   
1            2         1       1  Cumings, Mrs. Jo...  female  38.0      1      0   
2            3         1       3  Heikkinen, Miss....  female  26.0      0      0   

             Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_no  
0         A/5 21171   7.2500   NaN        S      0      220.0          2  
1          PC 17599  71.2833   C85        C      0      380.0          2  
2  STON/O2. 3101282   7.9250   NaN        S      0      260.0          1

In [70]:
# 기존 칼럼 업데이트
titanic_df['Age_by_10'] = titanic_df['Age_by_10'] + 100
titanic_df.head(3)

PassengerId  Survived  Pclass                 Name     Sex   Age  SibSp  Parch  \
0            1         0       3  Braund, Mr. Owen...    male  22.0      1      0   
1            2         1       1  Cumings, Mrs. Jo...  female  38.0      1      0   
2            3         1       3  Heikkinen, Miss....  female  26.0      0      0   

             Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_no  
0         A/5 21171   7.2500   NaN        S      0      320.0          2  
1          PC 17599  71.2833   C85        C      0      480.0          2  
2  STON/O2. 3101282   7.9250   NaN        S      0      360.0          1

### DataFrame 데이터 삭제

- drop() 메서드 이용
- DataFrame.drop(labels=None, axis=0, index=None, columns=None, level=None, inplace=False, errors='raise')
- 가장 중요한 파라미터는 labels, axis, inplace -> axis는 행/열 방향(0 = row, 1 = column)

In [71]:
titanic_drop_df = titanic_df.drop('Age_0', axis=1)
titanic_drop_df.head(3)

PassengerId  Survived  Pclass                 Name     Sex   Age  SibSp  Parch  \
0            1         0       3  Braund, Mr. Owen...    male  22.0      1      0   
1            2         1       1  Cumings, Mrs. Jo...  female  38.0      1      0   
2            3         1       3  Heikkinen, Miss....  female  26.0      0      0   

             Ticket     Fare Cabin Embarked  Age_by_10  Family_no  
0         A/5 21171   7.2500   NaN        S      320.0          2  
1          PC 17599  71.2833   C85        C      480.0          2  
2  STON/O2. 3101282   7.9250   NaN        S      360.0          1

In [72]:
# inplace parameter
titanic_df
# 원본 DF에 Age_0 칼럼이 그대로 남아있다.
titanic_df.drop('Age_0', axis=1, inplace=True)
titanic_df

PassengerId  Survived  Pclass                 Name     Sex   Age  SibSp  Parch  \
0              1         0       3  Braund, Mr. Owen...    male  22.0      1      0   
1              2         1       1  Cumings, Mrs. Jo...  female  38.0      1      0   
2              3         1       3  Heikkinen, Miss....  female  26.0      0      0   
3              4         1       1  Futrelle, Mrs. J...  female  35.0      1      0   
4              5         0       3  Allen, Mr. Willi...    male  35.0      0      0   
..           ...       ...     ...                  ...     ...   ...    ...    ...   
886          887         0       2  Montvila, Rev. J...    male  27.0      0      0   
887          888         1       1  Graham, Miss. Ma...  female  19.0      0      0   
888          889         0       3  Johnston, Miss. ...  female   NaN      1      2   
889          890         1       1  Behr, Mr. Karl H...    male  26.0      0      0   
890          891         0       3  Dooley, Mr. Patrick    male  32.0      0      0   

               Ticket     Fare Cabin Embarked  Age_by_10  Family_no  
0           A/5 21171   7.2500   NaN        S      320.0          2  
1            PC 17599  71.2833   C85        C      480.0          2  
2    STON/O2. 3101282   7.9250   NaN        S      360.0          1  
3              113803  53.1000  C123        S      450.0          2  
4              373450   8.0500   NaN        S      450.0          1  
..                ...      ...   ...      ...        ...        ...  
886            211536  13.0000   NaN        S      370.0          1  
887            112053  30.0000   B42        S      290.0          1  
888        W./C. 6607  23.4500   NaN        S        NaN          4  
889            111369  30.0000  C148        C      360.0          1  
890            370376   7.7500   NaN        Q      420.0          1  

[891 rows x 14 columns]

In [73]:
# 여러 개 칼럼 삭제
drop_result = titanic_df.drop(['Age_by_10', 'Family_no'], axis=1, inplace=True)
print('inplace=True로 drop 후 반환된 값 : ', drop_result)
titanic_df.head(3)

inplace=True로 drop 후 반환된 값 :  None


PassengerId  Survived  Pclass                 Name     Sex   Age  SibSp  Parch  \
0            1         0       3  Braund, Mr. Owen...    male  22.0      1      0   
1            2         1       1  Cumings, Mrs. Jo...  female  38.0      1      0   
2            3         1       3  Heikkinen, Miss....  female  26.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S

- drop 시 inplace=True로 설정하면 dataframe.drop()의 반환 값은 None이 된다. 따라서, titanic_df = titanic_df.drop(inplace=True)와 같이 다시 자신의 DataFrame 객체로 할당하면 안 된다. 다른 이름의 새 변수를 만들거나, 아예 변수 지정 없이 사용한다.

In [74]:
# axis = 0
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 20) # 출력 화면 설정

print('###### before axis 0 drop ######')
print(titanic_df.head(3))

titanic_df.drop([0, 1, 2], axis=0, inplace=True)
print('###### after axis 0 drop ######')
print(titanic_df.head(3))

###### before axis 0 drop ######
   PassengerId  Survived  Pclass                 Name     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr. Owen...    male  22.0      1      0         A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mrs. Jo...  female  38.0      1      0          PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, Miss....  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S
###### after axis 0 drop ######
   PassengerId  Survived  Pclass                 Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, Mrs. J...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. Willi...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3     Moran, Mr. James    male   NaN      0      0  330877   8.458

### Index 객체
- RDBMS의 PK와 유사하게 DF, Series의 레코드를 고유하게 식별하는 객체
- DataFrame.index 또는 Series.index

In [75]:
# 원본 파일 다시 로딩
titanic_df = pd.read_csv('C:/DATA_WORKS/PYTHON_WORKS/data/titanic_train.csv')
# Index 객체 추출
indexes = titanic_df.index
print(indexes)
# Index 객체를 실제 값 array로 변환
print('Index 객체 array값 : \n', indexes.values)

RangeIndex(start=0, stop=891, step=1)
Index 객체 array값 : 
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 2

- Index 객체는 식별성 데이터를 1차원 array로 가지며, ndarray와 유사하게 단일 값 반환 및 슬라이싱도 가능하다.

In [76]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6


In [77]:
# (오류) 아래와 같이 Index 객체 값을 변경하는 작업은 수행할 수 없다.
indexes[0] = 5

TypeError: Index does not support mutable operations

- Series 객체는 Index 객체를 포함하지만, Series 객체에 연산 함수를 적용할 때 Index는 연산에서 제외된다. Index는 오직 식별용으로만 사용

In [78]:
series_fare = titanic_df['Fare']
print('Fare Series max 값 : ', series_fare.max())
print('Fare Series sum 값 : ', series_fare.sum())
print('sum() Fare Series : ', sum(series_fare))
print('Fare Series + 3 : \n', (series_fare + 3).head(3))

Fare Series max 값 :  512.3292
Fare Series sum 값 :  28693.9493
sum() Fare Series :  28693.949299999967
Fare Series + 3 : 
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64


- reset_index() : 새롭게 인덱스를 연속 숫자 형으로 할당하며 기존 인덱스는 'index'라는 새로운 '칼럼'으로 추가

In [79]:
titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

index  PassengerId  Survived  Pclass                 Name     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0      0            1         0       3  Braund, Mr. Owen...    male  22.0      1      0         A/5 21171   7.2500   NaN        S
1      1            2         1       1  Cumings, Mrs. Jo...  female  38.0      1      0          PC 17599  71.2833   C85        C
2      2            3         1       3  Heikkinen, Miss....  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S

In [81]:
print('### before reset_index ###')
values_counts = titanic_df['Pclass'].value_counts()
print(value_counts)
print('value_counts 객체 변수 타입 : ', type(value_counts))
new_value_counts = value_counts.reset_index(inplace=False)
print('### after reset_index ###')
print(new_value_counts)
print('new_value_counts 객체 변수 타입 : ', type(new_value_counts))

# reset_index() 수행 후 class가 Series 에서 DataFrame으로 바뀐다.

### before reset_index ###
3    491
1    216
2    184
Name: Pclass, dtype: int64
value_counts 객체 변수 타입 :  <class 'pandas.core.series.Series'>
### after reset_index ###
   index  Pclass
0      3     491
1      1     216
2      2     184
new_value_counts 객체 변수 타입 :  <class 'pandas.core.frame.DataFrame'>


### 데이터 셀렉션 및 필터링
> [], ix[], iloc[], loc[]

**DataFrame의 [] 연산자**

- 넘파이의 [] 연산자 : 행의 위치, 열의 위치, 슬라이싱 범위 등을 지정해 데이터를 가져올 수 있다.
- DataFrame의 [] 연산자 : 칼럼명 문자(또는 칼럼명의 리스트 객체) 또는 인덱스로 변환 가능한 표현식. 기본적으로 칼럼만 지정

In [83]:
print('단일 칼럼 데이터 추출 : \n', titanic_df['Pclass'].head(3))
print('\n 여러 칼럼의 데이터 추출 : \n', titanic_df[['Survived', 'Pclass']]).head(3)
print('[ ] 안에 숫자 index는 KeyError 오류 발생 : \n', titanic_df[0])

단일 칼럼 데이터 추출 : 
 0    3
1    1
2    3
Name: Pclass, dtype: int64

 여러 칼럼의 데이터 추출 : 
      Survived  Pclass
0           0       3
1           1       1
2           1       3
3           1       1
4           0       3
..        ...     ...
886         0       2
887         1       1
888         0       3
889         1       1
890         0       3

[891 rows x 2 columns]


AttributeError: 'NoneType' object has no attribute 'head'

In [87]:
# 판다스의 인덱스 형태로 변환 가능한 표현식은 입력 가능
titanic_df[0:2]

PassengerId  Survived  Pclass                 Name     Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr. Owen...    male  22.0      1      0  A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mrs. Jo...  female  38.0      1      0   PC 17599  71.2833   C85        C

In [88]:
# 불린 인덱싱 표현
titanic_df[titanic_df['Pclass'] == 3].head(4)

PassengerId  Survived  Pclass                 Name     Sex   Age  SibSp  Parch            Ticket    Fare Cabin Embarked
0            1         0       3  Braund, Mr. Owen...    male  22.0      1      0         A/5 21171  7.2500   NaN        S
2            3         1       3  Heikkinen, Miss....  female  26.0      0      0  STON/O2. 3101282  7.9250   NaN        S
4            5         0       3  Allen, Mr. Willi...    male  35.0      0      0            373450  8.0500   NaN        S
5            6         0       3     Moran, Mr. James    male   NaN      0      0            330877  8.4583   NaN        Q

**명칭 기반 인덱싱과 위치 기반 인덱싱의 구분**
- 명칭(Label) 기반 인덱싱
- 위치(Position) 기반 인덱싱
- DataFrame의 인덱스 값은 명칭 기반 인덱싱이라고 간주해야 한다.

**DataFrame iloc[] 연산자**

- iloc() : 위치 기반 인덱싱만 허용 -> 행과 열 값으로 integer 또는 integer형의 슬라이싱, 팬시 리스트 값을 입력

In [93]:
data = {'Name' : ['Chulmin', 'Eunkyung', 'Jinwoong', 'Soobeom'],
       'Year' : [2011, 2016, 2015, 2015],
       'Gender' : ['Male', 'Female', 'Male', 'Male']
       }
data_df = pd.DataFrame(data, index=['one', 'two', 'three', 'four'])

# iloc[] 사용해 인덱싱
print(data_df.iloc[0, 0])

# 오류 1 : 칼럼 명 기준으로 열 인덱싱을 하는 경우
data_df.iloc(0, 'Name')
# 오류 2 : 문자열 인덱스를 행 위치에 입력하는 경우
data.df.iloc['one', 0]

Chulmin


TypeError: __call__() takes from 1 to 2 positional arguments but 3 were given

In [95]:
# data_df를 reset_index()로 새로운 숫자형 인덱스를 생성
data_df_reset = data_df.reset_index()
data_df_reset = data_df_reset.rename(columns={'index' : 'old_index'})

# 인덱스 값에 1을 더해서 1부터 시작하는 새로운 인덱스 값 생성
data_df_reset.index = data_df_reset.index+1
data_df_reset

old_index      Name  Year  Gender
1       one   Chulmin  2011    Male
2       two  Eunkyung  2016  Female
3     three  Jinwoong  2015    Male
4      four   Soobeom  2015    Male

In [97]:
# 정수형 인덱스 값으로 변경된 data_df_reset에 iloc 적용
data_df_reset.iloc[0, 1]

'Chulmin'

**DataFrame loc[] 연산자**

In [98]:
data_df.loc['one', 'Name']

'Chulmin'

In [101]:
data_df_reset.loc[1, 'Name']

'Chulmin'

- Slicing 적용 : 일반적인 slicing과 달리, loc[0:3]은 0~2까지가 아닌 0~3까지를 의미. (loc은 문자열 기반이기 때문)

In [102]:
print('위치 기반 iloc slicing \n', data_df.iloc[0:1, 0], '\n')
print('명칭 기반 loc slicing \n', data_df.loc['one':'two', 'Name'])
print(data_df_reset.loc[1:2, 'Name'])

위치 기반 iloc slicing 
 one    Chulmin
Name: Name, dtype: object 

명칭 기반 loc slicing 
 one     Chulmin
two    Eunkyung
Name: Name, dtype: object
1     Chulmin
2    Eunkyung
Name: Name, dtype: object


**불린 인덱싱**

In [104]:
titanic_df = pd.read_csv('C:/DATA_WORKS/PYTHON_WORKS/data/titanic_train.csv')
titanic_boolean = titanic_df[titanic_df['Age']>60]
print(type(titanic_boolean))
titanic_boolean

<class 'pandas.core.frame.DataFrame'>


PassengerId  Survived  Pclass                 Name     Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked
33            34         0       2  Wheadon, Mr. Edw...    male  66.0      0      0   C.A. 24579   10.5000          NaN        S
54            55         0       1  Ostby, Mr. Engel...    male  65.0      0      1       113509   61.9792          B30        C
96            97         0       1  Goldschmidt, Mr....    male  71.0      0      0     PC 17754   34.6542           A5        C
116          117         0       3  Connors, Mr. Pat...    male  70.5      0      0       370369    7.7500          NaN        Q
170          171         0       1  Van der hoef, Mr...    male  61.0      0      0       111240   33.5000          B19        S
252          253         0       1  Stead, Mr. Willi...    male  62.0      0      0       113514   26.5500          C87        S
275          276         1       1  Andrews, Miss. K...  female  63.0      1      0        13502   77.9583           D7        S
280          281         0       3     Duane, Mr. Frank    male  65.0      0      0       336439    7.7500          NaN        Q
326          327         0       3  Nysveen, Mr. Joh...    male  61.0      0      0       345364    6.2375          NaN        S
438          439         0       1    Fortune, Mr. Mark    male  64.0      1      4        19950  263.0000  C23 C25 C27        S
456          457         0       1  Millet, Mr. Fran...    male  65.0      0      0        13509   26.5500          E38        S
483          484         1       3  Turkula, Mrs. (H...  female  63.0      0      0         4134    9.5875          NaN        S
493          494         0       1  Artagaveytia, Mr...    male  71.0      0      0     PC 17609   49.5042          NaN        C
545          546         0       1  Nicholson, Mr. A...    male  64.0      0      0          693   26.0000          NaN        S
555          556         0       1   Wright, Mr. George    male  62.0      0      0       113807   26.5500          NaN        S
570          571         1       2   Harris, Mr. George    male  62.0      0      0  S.W./PP 752   10.5000          NaN        S
625          626         0       1  Sutton, Mr. Fred...    male  61.0      0      0        36963   32.3208          D50        S
630          631         1       1  Barkworth, Mr. A...    male  80.0      0      0        27042   30.0000          A23        S
672          673         0       2  Mitchell, Mr. He...    male  70.0      0      0   C.A. 24580   10.5000          NaN        S
745          746         0       1  Crosby, Capt. Ed...    male  70.0      1      1    WE/P 5735   71.0000          B22        S
829          830         1       1  Stone, Mrs. Geor...  female  62.0      0      0       113572   80.0000          B28      NaN
851          852         0       3  Svensson, Mr. Johan    male  74.0      0      0       347060    7.7750          NaN        S

In [105]:
titanic_df[titanic_df['Age'] > 60][['Name','Age','Sex','Survived']]

Name   Age     Sex  Survived
33   Wheadon, Mr. Edw...  66.0    male         0
54   Ostby, Mr. Engel...  65.0    male         0
96   Goldschmidt, Mr....  71.0    male         0
116  Connors, Mr. Pat...  70.5    male         0
170  Van der hoef, Mr...  61.0    male         0
252  Stead, Mr. Willi...  62.0    male         0
275  Andrews, Miss. K...  63.0  female         1
280     Duane, Mr. Frank  65.0    male         0
326  Nysveen, Mr. Joh...  61.0    male         0
438    Fortune, Mr. Mark  64.0    male         0
456  Millet, Mr. Fran...  65.0    male         0
483  Turkula, Mrs. (H...  63.0  female         1
493  Artagaveytia, Mr...  71.0    male         0
545  Nicholson, Mr. A...  64.0    male         0
555   Wright, Mr. George  62.0    male         0
570   Harris, Mr. George  62.0    male         1
625  Sutton, Mr. Fred...  61.0    male         0
630  Barkworth, Mr. A...  80.0    male         1
672  Mitchell, Mr. He...  70.0    male         0
745  Crosby, Capt. Ed...  70.0    male         0
829  Stone, Mrs. Geor...  62.0  female         1
851  Svensson, Mr. Johan  74.0    male         0

In [106]:
titanic_df.loc[titanic_df['Age'] > 60, ['Name', 'Age']]

Name   Age
33   Wheadon, Mr. Edw...  66.0
54   Ostby, Mr. Engel...  65.0
96   Goldschmidt, Mr....  71.0
116  Connors, Mr. Pat...  70.5
170  Van der hoef, Mr...  61.0
252  Stead, Mr. Willi...  62.0
275  Andrews, Miss. K...  63.0
280     Duane, Mr. Frank  65.0
326  Nysveen, Mr. Joh...  61.0
438    Fortune, Mr. Mark  64.0
456  Millet, Mr. Fran...  65.0
483  Turkula, Mrs. (H...  63.0
493  Artagaveytia, Mr...  71.0
545  Nicholson, Mr. A...  64.0
555   Wright, Mr. George  62.0
570   Harris, Mr. George  62.0
625  Sutton, Mr. Fred...  61.0
630  Barkworth, Mr. A...  80.0
672  Mitchell, Mr. He...  70.0
745  Crosby, Capt. Ed...  70.0
829  Stone, Mrs. Geor...  62.0
851  Svensson, Mr. Johan  74.0

- 복합 조건 결합하기
1. and 조건일 때는 &
2. or 조건일 때는 |
3. Not 조건일 때는 ~

In [109]:
# 복합 조건 결합
# 60세를 초과한 1등석 여성 조회
titanic_df[(titanic_df['Age']>60) & (titanic_df['Pclass']==1) &
           (titanic_df['Sex']=='female')]

PassengerId  Survived  Pclass                 Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Miss. K...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs. Geor...  female  62.0      0      0  113572  80.0000   B28      NaN

### 정렬, Aggregatation 함수, GroupBy 적용

**DataFrame, Series의 정렬 - sort_values()**
- RDBMS의 order by와 유사한 기능
- DataFrame.sort_values(by=['column'], ascending=True, inplace=False)

In [114]:
titanic_sorted = titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

PassengerId  Survived  Pclass                 Name     Sex   Age  SibSp  Parch     Ticket   Fare Cabin Embarked
845          846         0       3  Abbing, Mr. Anthony    male  42.0      0      0  C.A. 5547   7.55   NaN        S
746          747         0       3  Abbott, Mr. Ross...    male  16.0      1      1  C.A. 2673  20.25   NaN        S
279          280         1       3  Abbott, Mrs. Sta...  female  35.0      1      1  C.A. 2673  20.25   NaN        S

In [116]:
# 여러 개의 칼럼으로 정렬, 내림차순
titanic_sorted = titanic_sorted.sort_values(by = ['Fare', 'PassengerId'], ascending=False)
titanic_sorted.head(5)

PassengerId  Survived  Pclass                 Name     Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked
737          738         1       1  Lesurer, Mr. Gus...    male  35.0      0      0  PC 17755  512.3292         B101        C
679          680         1       1  Cardeza, Mr. Tho...    male  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C
258          259         1       1     Ward, Miss. Anna  female  35.0      0      0  PC 17755  512.3292          NaN        C
438          439         0       1    Fortune, Mr. Mark    male  64.0      1      4     19950  263.0000  C23 C25 C27        S
341          342         1       1  Fortune, Miss. A...  female  24.0      3      2     19950  263.0000  C23 C25 C27        S

**Aggregation 함수 적용**
- aggregation 함수 : min(), max(), sum(), count()
- DataFrame에서 바로 aggregationg을 호출하면 모든 칼럼에 해당 aggregation 적용

In [117]:
# 전체 칼럼 일괄 적용
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [118]:
# 특정 칼럼에만 적용
titanic_df[['Age', 'Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

**groupby() 적용**
- DataFrame.groupby() 호출 시 'DataFrameGroupBy' 라는 또 다른 형태의 DF 반환.

In [121]:
titanic_groupby = titanic_df.groupby(by = 'Pclass')
print(type(titanic_groupby), '\n', titanic_groupby)

<class 'pandas.core.groupby.generic.DataFrameGroupBy'> 


In [123]:
# groupby() 결과에 aggregation 호출하면 groupby() 대상 칼럼을 제외한 모든 칼럼에 집계 적용
# 대상 칼럼은 인덱스로
titanic_groupby = titanic_df.groupby('Pclass').count()
titanic_groupby

PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  Cabin  Embarked
Pclass                                                                                    
1               216       216   216  216  186    216    216     216   216    176       214
2               184       184   184  184  173    184    184     184   184     16       184
3               491       491   491  491  355    491    491     491   491     12       491

In [125]:
# 특정 칼럼만 보기
# groupby() -> Filtering -> Aggregation
titanic_groupby = titanic_df.groupby('Pclass')[['PassengerId', 'Survived']].count()
titanic_groupby

PassengerId  Survived
Pclass                       
1               216       216
2               184       184
3               491       491

In [128]:
# 둘 이상의 집계 함수를 쓸 때
titanic_df.groupby('Pclass')[['Age', 'Fare', 'Survived']].agg(['max', 'min', 'mean'])

Age                       Fare                 Survived              
         max   min       mean       max  min       mean      max min      mean
Pclass                                                                        
1       80.0  0.92  38.233441  512.3292  0.0  84.154687        1   0  0.629630
2       70.0  0.67  29.877630   73.5000  0.0  20.662183        1   0  0.472826
3       74.0  0.42  25.140620   69.5500  0.0  13.675550        1   0  0.242363

단, 이 경우 각각의 칼럼(Age, Fare, Survived)에 대해 모든 집계함수(max, min, mean)을 다 보여준다는 점에서 유연성은 떨어진다.
- 여러 칼럼에 서로 다른 aggregation 함수를 적용하려면 딕셔너리 활용

In [129]:
agg_format = {'Age':'mean', 'SibSp':'sum', 'Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

Age  SibSp       Fare
Pclass                             
1       38.233441     90  84.154687
2       29.877630     74  20.662183
3       25.140620    302  13.675550

### 결손 데이터 처리하기
- isna() : NaN 여부 확인하는 API
- fillna() : NaN 값을 다른 값으로 대체하는 API

**isna()로 결손 데이터 여부 확인**

In [130]:
titanic_df.isna().head(3)

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket   Fare  Cabin  Embarked
0        False     False   False  False  False  False  False  False   False  False   True     False
1        False     False   False  False  False  False  False  False   False  False  False     False
2        False     False   False  False  False  False  False  False   False  False   True     False

In [135]:
# 결손 데이터 개수 집계
# count를 쓰면 전체 행 수가 나온다.
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

**fillna()로 결손 데이터 대체하기**

In [138]:
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
# 위와 같이 반환 값을 다시 받아야 적용된다. 혹은 implace=True 파라미터 사용
titanic_df.head(3)

PassengerId  Survived  Pclass                 Name     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr. Owen...    male  22.0      1      0         A/5 21171   7.2500  C000        S
1            2         1       1  Cumings, Mrs. Jo...  female  38.0      1      0          PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, Miss....  female  26.0      0      0  STON/O2. 3101282   7.9250  C000        S

In [139]:
# 'Age' 결손 값은 평균 나이로, 'Embarked' 결손 값은 'S'로 대체
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

### apply lambda 식으로 데이터 가공
- 파이썬에서 함수형 프로그래밍(functional programming) 지원을 위해 만들어진 식

In [140]:
# 임의의 함수 설정
def get_squre(a):
    return a**2
print('3의 제곱은 : ', get_squre(3))

3의 제곱은 :  9


In [143]:
# 위 함수를 lambda 식으로 변환
lambda_square = lambda x : x**2
# ':' 왼쪽의 x는 입력 인자, 오른쪽은 입력 인자를 이용한 계산식(=반환 값)
print('3의 제곱은 : ', lambda_square(3))

3의 제곱은 :  9


- map() : lambda 식에서 여러 개의 값을 입력 인자로 사용해야 할 경우 사용

In [144]:
a = [1, 2, 3]
squares = map(lambda x : x**2, a)
list(squares)

[1, 4, 9]

In [145]:
titanic_df['Name_len'] = titanic_df['Name'].apply(lambda x : len(x))
titanic_df[['Name', 'Name_len']].head(3)

Name  Name_len
0  Braund, Mr. Owen...        23
1  Cumings, Mrs. Jo...        51
2  Heikkinen, Miss....        22

In [149]:
# lambda에 if else 절을 사용해 조금 더 복잡한 가공하기
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x : 'adult' if x >= 20 else 'child' )
titanic_df[['Name','Age', 'Child_Adult']].head(8)

Name        Age Child_Adult
0  Braund, Mr. Owen...  22.000000       adult
1  Cumings, Mrs. Jo...  38.000000       adult
2  Heikkinen, Miss....  26.000000       adult
3  Futrelle, Mrs. J...  35.000000       adult
4  Allen, Mr. Willi...  35.000000       adult
5     Moran, Mr. James  29.699118       adult
6  McCarthy, Mr. Ti...  54.000000       adult
7  Palsson, Master....   2.000000       child

In [154]:
# else if 여러 개
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : 'Child' if x <= 15 else ('Adult' if x <= 60 else 'Elderly'))
titanic_df['Age_cat'].value_counts()

Adult      786
Child       83
Elderly     22
Name: Age_cat, dtype: int64

In [157]:
# 별도의 함수로 세분화된 분류 처리
def get_category(age) : 
    cat = ''
    if age <= 5 : cat = 'Baby'
    elif age <= 12 : cat = 'Child'
    elif age <= 18 : cat = 'Teenager'
    elif age <= 25 : cat = 'Student'
    elif age <= 35 : cat = 'Young Adult'
    elif age <= 60 : cat = 'Adult'
    else : cat = 'Elderly'
        
    return cat

# lambda 식에 위에서 생성한 함수를 반환값으로 지정
# get_category(X)는 입력값으로 'Age'칼럼 값을 받아서 해당하는 cat 반환
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : get_category(x))
titanic_df[['Name', 'Age', 'Age_cat']].head(10)

Name        Age      Age_cat
0  Braund, Mr. Owen...  22.000000      Student
1  Cumings, Mrs. Jo...  38.000000        Adult
2  Heikkinen, Miss....  26.000000  Young Adult
3  Futrelle, Mrs. J...  35.000000  Young Adult
4  Allen, Mr. Willi...  35.000000  Young Adult
5     Moran, Mr. James  29.699118  Young Adult
6  McCarthy, Mr. Ti...  54.000000        Adult
7  Palsson, Master....   2.000000         Baby
8  Johnson, Mrs. Os...  27.000000  Young Adult
9  Nasser, Mrs. Nic...  14.000000     Teenager